### ISSUE TITLE
Feature: (Optionally) Cleanup unused signatures (db)

### ISSUE THREAD

**Issue by amishmm** [rseichter/fangfrisch#2]
Let us say I am using two sources for signatures - sanesecurity and urlhaus.

Tomorrow I decide that sanesecurity signature are not required or are to be disabled temporarily because there is some issue with them.

So I remove sanesecurity from fangfrisch.conf but old signatures will still remain in `/var/lib/clamav` and will continue to be used by clamav.

So can you provide a feature  where I run `fangfrisch cleanunusedsigs` and it cleans up files related to unused sources from `/var/lib/clamav`

It will check which data sources are enabled and delete files related to other databases which are not enabled. (ofcourse it should not delete other signature files which it has not downloaded but are there in `/var/lib/clamav`)

**Comment by rseichter** [comment]
I see at least the following cases to consider:

1. Disabling a whole provider section.

2. Removing 1..n `url_xyz` entries from a single provider section.

3. Removing 1..n `url_xyz` entries from multiple provider sections.

4. Adding or changing 1..n `file_xyz` entries.

There may be more scenarios, but these are the first that come to my mind. All of these can result in previously downloaded files becoming obsolete. Automatic cleanup would require keeping track of all files that were ever downloaded, plus what URLs and which providers they match. That's not trivial, and I also don't think it is worth the effort.

Perhaps you would consider the following alternative:

```shell
1> find /var/lib/clamav -type f -mtime +1 -delete
2> fangfrisch --conf /etc/fangfrisch.conf --force
```

Step one deletes signature files that have not been modified during the last 24 hours. Step two forces a fresh download of all active URLs. You can change `mtime` for a different cutoff date, and perhaps run `freshclam` as well after cleanup.

**Comment by amishmm** [comment]
I think it is very easy to maintain.

In SQL table refreshlog you need to add two more columns, called "source", "destfile".

Source will contain source of the signatures, i.e. sanesecurity, malwarepatrol etc.
Destination will contain file path i.e. /var/lib/clamav/foo.bar

When someone runs: `fangfrisch cleanunusedsigs`, this is what it will do:
1) Check fangfrisch.conf file to decide which sources are enabled and which are not.
2) If source is enabled, do nothing.
3) If source is disabled, then delete `destfile` for that `source` (if file exists)

Overall algorithm will be same as that for download.

Just that instead of enabled sources, it will pick disabled sources. And instead of downloading file, it will delete file.

**Comment by amishmm** [comment]
Once you implement above (per provider) feature. It will be easy to do step 2, 3, 4 (manually)

Admin can:
1. First disable provider
2. Run `fangfrisch cleanununsedsigs`. This will delete everything related to that provider.
3. Enable provider again, make whatever changes to url_xyz, file_xyz
4. Run `fangfrisch refresh`

Now we have clean database with only files that are needed.

Please think over.

**Comment by rseichter** [comment]
> I think it is very easy to maintain. (for a particular provider)

Enabling/disabling a provider section is but one of the scenarios I described, and the easiest one to handle. The approach you describe would not be "complete". The alternative I presented is provider-agnostic and covers more scenarios.

> Now we have clean database with only files that are needed.

What exactly are your goals? To remove unused signature files from disk, I presume? I'm not sure I understand the clean database part; are you bothered by having unused entries in the SQL database? The latter can be fixed at any time by deleting all records from the log table.

**Comment by amishmm** [comment]
Suppose I use sanesecurity and malwarepatrol. Both download numerous files and put it in `/var/lib/clamav` (which is used by clamav)

But then say tomorrow I do not want to use sanesecurity because say there is issue with signature (too many false positives or corrupt signature creating segfault in clamav) or paid license too costly or malwarepatrol is sufficient.

Then in such cases, I disable sanesecurity from fangfrisch.conf.  But old signatures of sanesecurity are still there in `/var/lib/clamav`. And so clamav will continue to use old signatures. (which I do not want)

So I need to delete those signatures from `/var/lib/clamav`. But there there will be way too many files (few from sanesecurity, few from malwarepatrol, few official clamav signatures). But I would not know which files are from sanesecurity and which from malwarepatrol.

So I need an option to clean such files easily.

That is why I suggested to add two columns to database called "provider", "destfile", which will track which file was downloaded from which provider.

Instead of my earlier proposal, I am proposing a much easier suggestion which would be much easy to implement, like this:

`fangfrisch cleanprovider sanesecurity`

And that command will forcefully delete all files related to that provider:
1. Find files from given provider:
`select destfile from refreshlog where provider = `sanesecurity`
2. Delete / clean the files:
`rm <destfile>`
3. Remove the provider from database:
`delete from refreshlog where provider = `sanesecurity`
4. Reload clamav

I hope I am able to convey it properly.

Thank you

**Comment by rseichter** [comment]
> I need to delete those signatures from /var/lib/clamav. [...] But I would not know which files are from sanesecurity and which from malwarepatrol.

That seems to be the part where our approach differs most. Using the method I proposed, one would not need to know which signature file was obtained from which provider.

1. Stop periodic updates for fangfrisch and freshclam
2. Disable provider(s) in fangfrisch.conf
3. Delete /var/lib/clamav/*
4. Launch "freshclam --foreground" once
5. Launch "fangfrisch --force refresh" once
6. Start periodic updates for fangfrisch and freshclam

These steps could even be executed in a shell script. However, how often is this used? I have not once "retired" a provider, but rather spent some time before adding specific providers in the first place to figure out if their data suits my needs.

Of course there are valid reasons to disable a provider after the fact, some of which you have mentioned. Still, what makes me pensive is the question "how often is this needed?" and, more importantly, the knowledge that a complete cleanup covering all use cases I mentioned before is difficult to achieve. Tracking renames etc. touches on what version control systems need to do, and even Subversion or Git rely on users executing `$VCSTOOL mv oldpath newpath` or similar.

**Comment by amishmm** [comment]
Your steps will lead to downtime of a critical component of a system for about 5 minutes atleast. And when you are maintaining 10-15 systems, it is not easy or efficient thing to do.

And why delete ALL the signatures just to delete a provider.

I can understand that you do not have inclination to implement the feature. But can you alteast add two columns "provider", "destfile" in database? (I do not know python else I would have dont a PR)

Once those two columns are added then I can write a shell script to do the necessary clean up.

Thank you

**Comment by rseichter** [comment]
> Your steps will lead to downtime of a critical component of a system for about 5 minutes atleast.

Fair point. I had not considered that to be a problem, because critical systems usually come with redundancy.

> And why delete ALL the signatures just to delete a provider.

Because it is the only way to ensure that no clutter remains. It is either that or tracking every file ever downloaded. You seem to repeatedly gloss over the question of renamed files, shared file names across providers (over time), etc. 😉

> I can understand that you do not have inclination to implement the feature.

That's not actually the case. If I can come up with a satisfactory solution that covers more than the simplest of use cases, why would I not add the feature? I am still musing about how to get it done in an acceptable manner.

It is definitely not about me being lazy or unwilling per se. In fact, if somebody opened a ready-made pull request, I would still not accept it if I considered the method half-assed, pardon my French. It is an interesting problem to crack. As long as I don't close this issue, you can be sure that I keep thinking about the proposal, and I find the discussion with you fruitful. I hope that it is not frustrating for you, that is definitely not my intent.

**Comment by rseichter** [comment]
I have been testing some ideas, trying to help you achieve your goal without having Fangfrisch shouldering the responsibility for deleting files. Does the following look useful to you?
```
→ fangfrisch -c /etc/fangfrisch.conf dumppaths | awk '/^securiteinfo/ {print $3}'
/var/lib/clamav/securiteinfoandroid.hdb
/var/lib/clamav/securiteinfoascii.hdb
/var/lib/clamav/securiteinfohtml.hdb
/var/lib/clamav/javascript.ndb
/var/lib/clamav/securiteinfopdf.hdb
/var/lib/clamav/securiteinfo.hdb
/var/lib/clamav/securiteinfo.ign2
```
The experimental `dumppaths` action processes the configuration like `refresh` would, but instead of downloading or changing things, it just prints three-tuples **(sectionname, url, localpath)** using horizontal tabulators as separators.

The output can be piped into `awk` or other utilities. In the example above, all local files of the parsed `[securiteinfo]` section are printed, which could then obviously be used to delete the files or whatever else you might require.

This appeals to me because Fangfrisch only needs to dump parts of a user-specified configuration file in a specific way, for other software to consume the output. I won't need to concern myself with tracking files, URLs, providers or combinations thereof over time. Users can use version control for their fangfrisch.conf (I do that for all content of `/etc`), but that remains out of scope for Fangfrisch.

Would you be willing to test a version that contains this functionality?

**Comment by amishmm** [comment]
Your idea is helpful but I would like to know what is wrong with my idea of adding two columns?

When fangfrisch downloads and saves a signature file, currently it stores URL, digest and timestamp in refreshlog.

At the same time, it can also add `provider` and `localpath`. And it becomes so easy to track the signatures which were downloaded by fangfrisch for a provider.

With this approach. My shell script can simply run `select localpath from refreshlog where provider = "securiteinfo"` and delete the files mentioned in `localpath`.

With dumppaths there are two issues that I can see.

Say in past file xyz.ndb was downloaded by securiteinfo but then in future that file was no longer part of securiteinfo. So in future dumppaths will not list that file ever. And that file will never be deleted. (but with my approach that file will still be there in database and hence be listed)

Also another thing with your approach is that when you grep output of dumppaths for /securiteinfo/. But now lets say if malwarepatrol also has a file whose URL or name contained word 'secuiteinfo', that will also get be listed and that will also be deleted! (I know grep-ing can be improved by using split on comma etc. but its additional coding)

But I must say that if you still want to provide dumppaths way, I can go ahead and test it.

**Comment by rseichter** [comment]
> I would like to know what is wrong with my idea of adding two columns?

What you are trying to achieve is not possible by simply extending records. Remember that the URL is the primary DB key. Relying on the existing refresh log, with extra columns or without, means you could only ever see where the latest successful refresh operation for a particular URL wrote data, not where that data was written in the past. That's not your fault, the required data is just not kept around.

My approach instead relies on fangfrisch.conf, which you can pass as an argument. That means historical URL-to-file mappings remain available as long as you keep the config file around that was used by Fangfrisch at the time.

With a version controlled config file one can actually reconstruct the past, which is not possible with a database that is overwritten constantly. Like I said, I keep all files in /etc (on all servers) in version control anyway. With 'dumppath' I can print the mappings as they were weeks ago, and when I simply pass in /etc/fangfrisch.conf I can see what paths were used for the latest refresh. It just works.

> another thing with your approach is that when you grep output of dumppaths for /securiteinfo/.

I don't. My `awk` match uses `^securiteinfo`, anchoring at the beginning of each line of text, i.e. the section name. I'd actually use `^securiteinfo\t` in live scripts, so only one section name can ever be matched. The following works as-is in Bash, no coding or changes required, as I just tested:
```
fangfrisch -c /etc/fangfrisch.conf dumppaths | awk '/^SOMEPROVIDER\t/ {print $3}' | xargs /bin/rm
```

**Comment by amishmm** [comment]
I am not sure if expecting that every user of fangfrisch will keep version controlled fangfrisch.conf is right thing to do.

A software should be self sufficient independent of external assumptions.

If you can not store data in refreshlog then you can simply create a new table (say `storelog`) in database, which tracks `provider` and `localpath`. (You might as well store timestamp if you want, which may come handy for some other feature)

This can be updated by `Insert or replace` sqlite command.
https://www.sqlitetutorial.net/sqlite-replace-statement/

> where the latest successful refresh operation for a particular URL wrote data, not where that data was written in the past.

I thought particular unique URL will always store data in same unique place. (as long as someone does not change path to clamav directory)

But based on your statement it appears that it can change?

So if url foo, stores file in foo but next fetch stores file in bar, then old file named foo will remain there forever? And foo may have several duplicate signatures with bar? And then clamav will load foo as well as bar?

**Comment by rseichter** [comment]
> I am not sure if expecting that every user of fangfrisch will keep version controlled fangfrisch.conf is right thing to do.

It is definitely not something I would or should expect, unless this assumption is explicitly documented. I mentioned versioning the config file as a simple means to solve the issue you currently have with retiring a provider, in a robust manner, because I already use config version control anyway.

The fact that Fangfrisch in its current state does not keep a log of where files were written over time is the reason for me wrestling with the "How to cleanup reliably?" question since you first filed your proposal. I am not looking for a quick win, but for a method that covers the most important use cases. Perhaps now you can better understand why I appear so hesitant.

> If you can not store data in refreshlog then you can simply create a new table (say storelog) in database, which tracks provider and localpath.

That is one of the possibilities I was considering. However, after getting some much-needed sleep I think I might be able to pull it off with less recorded history. I will experiment with a related idea of mine later today.

> I thought particular unique URL will always store data in same unique place.

That is the default behaviour. Fangfrisch will extract the file name from each URL. However, the flexibility of user-defined `file_xyz` mappings bites me in the bum here. I added this feature to support providers with atypical URLs. Users can, at any time, map URLs to specific local files. Doing that is of course a conscious decision made by the user, meaning that the user is responsible for cleaning up potential older data.

Freshclam does not address this issue, by the way, and not being able to define proper local file names has been causing people headaches for a long time.

**Comment by amishmm** [comment]
Ok let me know if you can provide any solution. I can try it once implemented.

**Comment by rseichter** [comment]
You can now access a [developer test release](https://test.pypi.org/project/fangfrisch/) that includes both an automatic self-cleanup feature and a new action called **dumpmappings**.

I would like to deliberately not explain what I did at this point, because I have also updated the [documentation](https://rseichter.github.io/fangfrisch/) and would like to know if you consider it sufficient.

**Comment by amishmm** [comment]
I tried dev5 version. I dropped table refreshlog and re-ran "initdb". And 2 new columns appeared.

**dumpmappings** seems to running correctly.

But I am not sure what you mean by automatic self-cleanup.

My `fangfrisch.conf` contains:
```
[DEFAULT]
db_url = sqlite:////var/lib/fangfrisch/db.sqlite
local_directory = /var/lib/clamav
on_update_exec = clamdscan --reload

[sanesecurity]
enabled = yes

[urlhaus]
enabled = yes

[malwarepatrol]
enabled = no
receipt = you_forgot_to_configure_receipt

[securiteinfo]
enabled = no
customer_id = you_forgot_to_configure_customer_id
```

First I did: (forced refresh)
`sudo -u clamav /usr/bin/fangfrisch --conf /etc/fangfrisch/fangfrisch.conf -f refresh`

Then I changed `enabled = no` for `urlhaus`

Then I did: (normal refresh)

`sudo -u clamav /usr/bin/fangfrisch --conf /etc/fangfrisch/fangfrisch.conf refresh`

But I was expecting that file `/var/lib/clamav/urlhaus.ndb` will be deleted by automatic self-cleanup. But it did not.

Did I misunderstand anything?

**Comment by rseichter** [comment]
Sorry, my bad. Yesterday I forgot to merge the latest changes from my feature branch before creating the dev5 distribution from the master branch. Could you please try again, using the version I just published?

**Comment by amishmm** [comment]
Sure I will try it by tomorrow. But in the mean time, can you make auto-cleanup optional in configuration file? Because not everyone may want that feature.

Say for example: (`fangfrisch.conf`)

```
[DEFAULT]
auto_clean_signatures = true
```
Also I see that you are making `initdb` to drop the existing data. I think it should happen only if user provides `-f` option to `initdb`. Otherwise user can accidentally delete the existing database.

**Comment by rseichter** [comment]
Behaviour in version 1.1.0.dev8 is now as follows:
* `initdb` does not drop DB tables.
* `--force initdb` drops DB tables.

I have also added a new configuration option:
```
[DEFAULT]
cleanup = default
```
Automatic cleanup can be disabled either globally or per provider using `cleanup = disabled`, but is enabled by default.

**Comment by amishmm** [comment]
Sorry for many suggestions. But `cleanup =` currently allows, `auto`, `automatic`, `default`, but it should also accept `true`, `on` and `yes`. Just like it allows `false`, `off`, `no`.

I will try dev8 today and report back.

**Comment by rseichter** [comment]
No worries, suggestions are fine. In this particular case, allowing only auto/automatic/default is deliberate, because `cleanup` is not meant to be a yes/no type of option. I have toyed with an alternative cleanup method I might come back to in the future. Anyway, only `default` and `disabled` are documented choices, the others are pure convenience.

**Comment by amishmm** [comment]
Tested `cleanup` option. And seems to be working fine as documented.

However there can be slight confusion with `default` option.

Suppose I have `fangfrisch.conf` like this:
```
[DEFAULT]
cleanup = disabled

[sanesecurity]
enabled = no
cleanup = default```

By common sense, I may believe that `cleanup = default` will pick whatever is mentioned for cleanup under `[DEFAULT]` section.

So in above example, I may expect that `cleanup` for `[sanesecurity]` will actually be `disabled`. But in reality it would be set to `auto`.(i.e. files will be deleted)

I understand this is minor issue but just mentioning incase you have a way to avoid such confusion.

**Comment by amishmm** [comment]
> EDIT: If you would like me to mention your real name instead of "Amish" in the change log, please let me know.

@amishmm would be fine. Thank you.

**Comment by rseichter** [comment]
> By common sense, I may believe that `cleanup = default` will pick whatever is mentioned for cleanup under `[DEFAULT]` section.

I consider that unlikely, because it is well documented how inheritance/overriding works. Fangfrisch documentation already contains a link pointing to Python's **configparser** package. However, changing to `cleanup = default` is of course very easy and might help avoiding confusion.

> Btw thank you for this feature and also great that you code them quickly.

You're welcome. Also, bouncing ideas back and forth with you gives me additional perspective on end user experience, so I thank you for that.

**Comment by amishmm** [comment]
Ok you may close this feature request. As I think it is complete.

Thanks again.
