### ISSUE TITLE
privacy

### ISSUE THREAD

**Issue by alexmyczko** [rseichter/fangfrisch#22]
you might want to drop the google stuff?

W: fangfrisch: privacy-breach-generic [<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=open+sans:300,300italic,400,400italic,600,600italic%7cnoto+serif:400,400italic,700,700italic%7cdroid+sans+mono:400,700">] (https://fonts.googleapis.com/css?family=open+sans:300,300italic,400,400italic,600,600italic%7cnoto+serif:400,400italic,700,700italic%7cdroid+sans+mono:400,700) [usr/share/doc/fangfrisch/index.html]

**Comment by rseichter** [comment]
What exactly seems to be your issue? Please see the [documentation](https://rseichter.github.io/fangfrisch/#_support) regarding how to report problems.

**Comment by rseichter** [comment]
Oh, that. Both the PDF- and HTML-documentation are generated using Asciidoctor, and in its default settings, that means Google web fonts. Personally, I don't consider this a problem.

**Comment by alexmyczko** [comment]
I see, well it is the debian lintian tool warning about it..

**Comment by rseichter** [comment]
If this worries you, you could re-generate the documentation and pass a custom stylesheet to Asciidoctor, or disable the use of Google webfonts. Alternatively, you could link to the online documentation instead of bundling the HTML docs, thereby avoiding responsibility for the content. Lastly, perhaps choose to only bundle the PDF?
