### ISSUE TITLE
comparison

### ISSUE THREAD

**Issue by alexmyczko** [rseichter/fangfrisch#23]
how is this different from clamav-unofficial-sigs ?

anyways, enjoy: http://sid.ethz.ch/debian/fangfrisch/

**Comment by rseichter** [comment]
Thank you. I wrote Fangfrisch because I needed a secure, extensible and easy-to-configure replacement for clamav-unofficial-sigs in production environments for me and my customers. Fangfrisch never needs to run as root, among other things. Beyond that, just compare the code, and decide for yourself which utility you trust more. Gentoo Linux, for example, also considers c-u-s [not a secure option](https://wiki.gentoo.org/wiki/ClamAV_Unofficial_Signatures).

**Comment by alexmyczko** [comment]
Maybe you want to comment on https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037250 ?
